{
 "title": "human-detection",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cameras",
    "label": "Cameras",
    "query": "cam1 : %{namespace}%/camera1, cam2 : %{namespace}%/camera2"
   },
   { "name": "cameras_selected", "query": "(cam1|cam2)" }
  ]
 },
 "panels": [
  {
   "title": "Realtime Monitoring",
   "type": "dellemc-pravegavideoplayer-panel",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Computer vision-based Human Detection",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_camera",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "camera" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "human",
     "query": "from(bucket: \"test\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"queue\" and\n    r._field == \"length\" and\n    r.camera == \"${cameras:text}\"\n  )",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "camera", "operator": "=~", "value": "/^${cameras_selected:raw}$/" }
     ]
    }
   ]
  },
  {
   "title": "Selected Clips",
   "type": "dellemc-pravegavideoplayer-panel",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$cameras # of human",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
   "repeat": "cameras",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Hour",
     "groupBy": [
      { "params": [ "camera" ], "type": "tag" }
     ],
     "measurement": "human",
     "query": "SELECT mean(\"count\") AS \"Per Hour\" FROM \"human\" WHERE (\"camera\" =~ /^${cameras:text}$/ AND \"time\" >= (now() - 1h)) GROUP BY \"camera\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "Per Hour" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "camera", "operator": "=~", "value": "/^${cameras_selected:raw}$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "(now() - 1h)" }
     ]
    },
    {
     "alias": "Peak Hour",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "camera" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "human",
     "query": "select max(\"Per Day\") from (SELECT mean(\"count\") AS \"Per Day\" FROM \"human\" WHERE (\"camera\" =~ /^${cameras:text}$/ AND \"time\" >= (now() - 1d))  GROUP BY time(1h), \"camera\" fill(null)) GROUP BY \"camera\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Per Day" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "camera", "operator": "=~", "value": "/^${cameras_selected:raw}$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "(now() - 1d)" }
     ]
    }
   ]
  },
  {
   "title": "Avg # of Human Over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_camera",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "camera" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "human",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "camera", "operator": "=~", "value": "/^${cameras_selected:raw}$/" }
     ]
    }
   ]
  },
  {
   "title": "$cameras # of human",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current Hour",
     "groupBy": [
      { "params": [ "camera" ], "type": "tag" }
     ],
     "measurement": "human",
     "query": "SELECT mean(\"count\") AS \"Per Hour\" FROM \"human\" WHERE (\"camera\" =~ /^${cameras:text}$/ AND \"time\" >= (now() - 1h)) GROUP BY \"camera\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "Per Hour" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "camera", "operator": "=~", "value": "/^${cameras_selected:raw}$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "(now() - 1h)" }
     ]
    },
    {
     "alias": "Peak Hour",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "camera" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "human",
     "query": "select max(\"Per Day\") from (SELECT mean(\"count\") AS \"Per Day\" FROM \"human\" WHERE (\"camera\" =~ /^${cameras:text}$/ AND \"time\" >= (now() - 1d))  GROUP BY time(1h), \"camera\" fill(null)) GROUP BY \"camera\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Per Day" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "camera", "operator": "=~", "value": "/^${cameras_selected:raw}$/" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "(now() - 1d)" }
     ]
    }
   ]
  }
 ]
}