{{- if .Values.enabledComponents.simulatedCamera }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.recorderPipeline.secret.name }}
  labels:
    sdp.dellemc.com/type: camera
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.global.recorderPipeline.secret.username | b64enc }}
  password: {{ .Values.global.recorderPipeline.secret.password | b64enc }}
{{- end}}
