{{- if .Values.stageTags.stage1 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.rtspSimulator.secret.name }}
  labels:
    sdp.dellemc.com/type: camera
type: kubernetes.io/basic-auth
data:
  # Replace these placeholders with your base64-encoded values
  username: {{ .Values.global.rtspSimulator.secret.username | b64enc }}
  password: {{ .Values.global.rtspSimulator.secret.password | b64enc }}
{{- end}}
