{{- if .Values.enabledComponents.recorderPipeline }}
apiVersion: gstreamer.dellemc.com/v1alpha1
kind: CameraRecorderPipeline
metadata:
  name: camera-recorder-2
spec:
  state: Running
  camera:
    address: {{ .Values.global.recorderPipeline.address | default "{{ $.Release.Name }}-rtsp-simulator.{{ $.Release.Namespace }}.svc.cluster.local" | quote }}
    path: {{ .Values.global.recorderPipeline.path2 | quote }}
    port: {{ .Values.global.recorderPipeline.port | quote }}
    secret: {{ .Values.global.recorderPipeline.secret.name | quote }}
  pravega:
    stream: {{ .Values.global.recorderPipeline.stream2 | quote }}
    retentionPolicy:
      retentionPolicyType: {{ .Values.global.recorderPipeline.rententionPolicyType | quote }}
      retentionDays: {{ .Values.global.recorderPipeline.rententionDays }}
  env:
   - name: CAMERA_PROTOCOLS 
     value: "tcp"
{{- end}}
