apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-grafana
  annotations:
    nautilus.dellemc.com/http-ingress: grafana
    nautilus.dellemc.com/http-ingress-name: {{ $.Release.Name }}-grafana
spec:
  ports:
  - name: grafana
    port: 3030
    targetPort: grafana
    protocol: TCP
  selector:
    release: {{ $.Release.Name }}-grafana
  type: ClusterIP
