apiVersion: nautilus.dellemc.com/v1alpha1
kind: Project
metadata:
  name: {{ $.Release.Namespace }}
spec:
  features:
    - name: pravegavideoserver
    - name: metrics
  metrics:
    enabled: false
  storage:
    persistentVolumeClaim:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs
    reclaimPolicy: Delete
