{{- if .Values.enabledComponents.simulatedCamera }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-rtsp-simulator
spec:
  ports:
  - name: rtsp
    port: {{ $.Values.global.camera.port }}
    targetPort: {{ $.Values.global.camera.port }}
    protocol: TCP
  selector:
    release: {{ $.Release.Name }}-rtsp-simulator
  type: ClusterIP
{{- end}}
